services:
  - type: web
    name: vector
    env: python
    plan: free # Use Render's free tier
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
